### ISSUE TITLE
broken link to releases download

### ISSUE THREAD

**Issue by tooptoop4** [yahoojapan/presto_exporter#10]
Binary can be downloaded from Releases page.

**Comment by yuokada** [comment]
Hi @tooptoop4 

I'm ex-repository owner.
It's not broken. There are just no explicit release yet.

**Comment by yuokada** [comment]
CC: @oneonestar , @sunjiangjing

**Comment by silvermissile** [comment]
presto web UI has already  the items listed in "Prometheus Metrics Details" .

[https://www.datadoghq.com/blog/monitor-presto-with-datadog/](expecte the view here )

**Comment by elonlo** [comment]
Has any development plan now?

**Comment by sunjiangjing** [comment]
@elonlo Sorry to reply later.
we have already stopped the new development plan in my team.

**Comment by elonlo** [comment]
@sunjiangjing okay, i get.

**Comment by tooptoop4** [comment]
:-(

**Comment by yuokada** [comment]
@sunjiangjing Why don't you make this repository archived if you have aborted new developments.

- en: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories
- ja: https://docs.github.com/ja/github/creating-cloning-and-archiving-repositories/archiving-repositories

**Comment by oneonestar** [comment]
This project has been deprecated. Please consider using [jmx_exporter](https://github.com/prometheus/jmx_exporter) instead.
