### ISSUE TITLE
Add the https and shared secret authentication support

### ISSUE THREAD

**Issue by alexku7** [yahoojapan/presto_exporter#13]
Hello

We are using the presto with HTTPS only with internal shared secret for the authentication between the presto's components like described here https://prestosql.io/docs/current/security/internal-communication.html

Is it possible to add this support to the exporter so it will be able to scrape the metrics from the https with authentication ?

**Comment by oneonestar** [comment]
This project has been deprecated. Please consider using [jmx_exporter](https://github.com/prometheus/jmx_exporter) instead.
